Much improved clocks and port
Carbonhell/Hippie-Rebase pull request #80
Opened 2017-01-22 05:53 UTC by tortellinitony

Adds clocks, drastically improved from those on Hippie before. New *animated* sci-fi icon.
http://i.imgur.com/094v804.png

Don't like it? You can break them now.
http://i.imgur.com/zYqqNXa.png

The bar and certain areas have a special analog clock.
http://i.imgur.com/JPcsaGm.png

The two previous bugs have been squashed.

2017-01-24 03:29 UTC, tortellinitony commented
I have to do something about the map

2017-01-26 02:44 UTC, tortellinitony commented
map merger doesn't FUCKING WORK

2017-01-26 17:45 UTC, Pyko1 commented
thats because my map pr makes changes all around the map.

2017-01-28 19:30 UTC, tortellinitony commented
Map works.

2017-01-31 21:06 UTC, j-mie requested changes

2017-01-31 21:06 UTC, JamieH commented on _maps/map_files/TgStation2/tgstation.2.1.3.dmm
> +	health = 9999;
Why does the clock have 9999 health?

2017-01-31 21:06 UTC, JamieH commented on _maps/map_files/TgStation2/tgstation.2.1.3.dmm
> +	health = 9999;
9999 health?

2017-01-31 21:06 UTC, JamieH commented on _maps/map_files/TgStation2/tgstation.2.1.3.dmm
> +	health = 9999;
9999 health?

2017-01-31 22:08 UTC, tortellinitony commented
no broken icon for the bar clock

2017-02-01 16:16 UTC, j-mie approved these changes

2017-02-01 16:16 UTC, JamieH commented
Fix the merge conflict

2017-02-01 21:52 UTC, tortellinitony commented
Conflicts resolved

2017-02-02 13:11 UTC, merged