Fixes two potential crash exploits
Carbonhell/Hippie-Rebase pull request #93
Opened 2017-01-29 02:07 UTC by tortellinitony

2017-01-29 17:53 UTC, ArcLumin commented
muh code

2017-01-29 18:18 UTC, tortellinitony commented
and creeper joe's

2017-01-31 08:21 UTC, JohnGinnane commented
Code looks good but couldn't you move the dire used stuff After the switch instead of repeating the same checks?

2017-01-31 20:10 UTC, Carbonhell requested changes

2017-01-31 20:10 UTC, Carbonhell commented on code/datums/wires/wires.dm
> +				wireused = 1
Use true/false if possible, it's cleaner and easier to understand.

2017-01-31 20:10 UTC, Carbonhell commented on code/datums/wires/wires.dm
> +				wireused = 1
same

2017-01-31 20:10 UTC, Carbonhell commented on code/datums/wires/wires.dm
> +				spawn(wire_cooldown)
Actually, you can just move this code outside the if checks to avoid having to copypaste it in each option. You should do that.

2017-01-31 20:10 UTC, Carbonhell commented on code/modules/power/singularity/containment_field.dm
> +//	var/datum/effect_system/spark_spread/s = new /datum/effect_system/spark_spread
Just delete the code altogether, uncommenting it clutters the dm file.

2017-02-01 03:13 UTC, tortellinitony commented
Changes are done

2017-02-01 16:12 UTC, merged