Reverts TG genetics rebalancing
Carbonhell/Hippie-Rebase pull request #95
Opened 2017-01-29 19:13 UTC by banthebantz

Reverts a series of changes by TG that nerfed tk to the point of uselessness and hulk rather significantly.

Also they changed dwarfism, for some reason.

2017-01-29 22:49 UTC, QuarianCommando commented
You know, those hulk changes they made don't seem too bad. Of course their 100% /hugbox/station, and terrible for regular servers, but we live in the land of Taylor Swift genetics.

2017-01-30 16:01 UTC, banthebantz commented
Please refer yourself to this thread: http://hippiestation.com/showthread.php?tid=5472&highlight=hulk

And this thread: http://hippiestation.com/showthread.php?tid=4561&highlight=hulk

Community opinion is pretty mixed but generally tips towards keeping hulk as it is considering the people calling for a nerf are just salty they got killed. Thus I find it only logical to revert hulk to how it has always been for years now.

2017-01-31 06:19 UTC, QuarianCommando commented
I mean, I guess it's on the admin team. They're the ones who will have to dill with the 6 gorillion ahelps from salty hulk players who get lazered to death for being shits every time someone competent runs genetics.

2017-01-31 15:59 UTC, banthebantz commented
It's standard practice to crit hulks in order to restrain, removing their stun punch =/= increased ahelps

2017-01-31 20:07 UTC, Carbonhell requested changes

2017-01-31 20:07 UTC, Carbonhell commented on code/_onclick/telekinesis.dm
> +	if(!istype(target, /turf) && istype(focus,/obj/item) && target.Adjacent(focus))
changing isturf to istype(x, /turf) is unnecessary, really. isturf is actually cleaner, keep it.

2017-01-31 20:07 UTC, Carbonhell commented on code/_onclick/telekinesis.dm
> +	if(!istype(target,/obj))
Isobj is better.

2017-01-31 20:07 UTC, Carbonhell commented on code/datums/mutations.dm
> +	owner.ventcrawler = 1
Can ventcrawler be something other than 0/1? If no, use true/false.

2017-01-31 20:07 UTC, Carbonhell commented on code/datums/mutations.dm
> +	owner.ventcrawler = 0
Same.

2017-02-01 15:54 UTC, banthebantz commented on code/datums/mutations.dm
> +	owner.ventcrawler = 1
Yes it can and in fact TG broke ventcrawl 1 because the item check doesn't discriminate organs, I'm fixing this shit as we speak

2017-02-02 12:47 UTC, merged